name: ephmrl-dev-eks

on:
  repository_dispatch:
    types: [ephmrl-dev-eks]

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read  

jobs:
  developer-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::586098609239:role/GitHubActionsRole
          role-session-name: GitHub-Actions-OIDC-Session
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false

      - name: Check passed in variables
        run: |
          echo "Payload received: ${{ github.event.client_payload.config }}"
          echo "--------------------------------"
          echo "Parameters received from repository dispatch event:"
          echo "##"
          echo "Environment: ${{ github.event.client_payload.config.environment }}" >> GITHUB_ENV
          echo "ClusterName: ${{ github.event.client_payload.config.projectName }}" >> GITHUB_ENV
          echo "Region: ${{ github.event.client_payload.config.region }}"   >> GITHUB_ENV
          echo "InstanceType: ${{ github.event.client_payload.config.instanceType }}"  >> GITHUB_ENV
          echo "tfvars file: ${{ github.event.client_payload.config.tfvarsFile }}"  >> GITHUB_ENV
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false
      
      - name: Terraform Init
        working-directory: ./environments/${GITHUB_ENV.environment}
        run: |
          terraform init -upgrade
      - name: Terraform Validate
        working-directory: ./environments/${GITHUB_ENV.environment}
        run: terraform validate 
      - name: Terraform Plan
        working-directory: ./environments/${GITHUB_ENV.environment}
        run: |
          terraform plan -var-file=${GITHUB_ENV.tfvarsFile} -out=ephemeral-${GITHUB_ENV.environment}-eks.tfplan      