name: ephmrl-dev-eks

on:
  repository_dispatch:
    types: [ephmrl-dev-eks]

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: "us-east-1"
  ENVIRONMENT: ${{ github.event.client_payload.config.environment }}
  CLUSTER_NAME: ${{ github.event.client_payload.config.projectName }}
  tfvarsFilename: "${{ github.event.client_payload.config.projectName }}.tfvars"

permissions:
  id-token: write
  contents: read  

jobs:
  developer-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::586098609239:role/GitHubActionsRole
          role-session-name: GitHub-Actions-OIDC-Session
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false

      - name: config_variables
        working-directory: ./environments/${{ env.ENVIRONMENT }}
        run: |
          pwd
          PAYLOAD=$(printf '%s' '${{ tojson(github.event.client_payload.config) }}')
          echo "Current Payload: $PAYLOAD"
          echo "--------------------------------"
          printf '%s' "$PAYLOAD" | jq -r 'to_entries[] |
            if .key == "network" then
              .value | to_entries[] |
              "\(.key)=\(.value | tojson)"
            else
              "\(.key)=\(.value)"
            end' > ${{ env.tfvarsFilename }}
          echo "--------------------------------"
          find /home/runner/work/Infrastructure/Infrastructure/environments/${{ env.ENVIRONMENT }} -type f | sort
          cat ${{ env.tfvarsFilename }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

    # Deploy Network
      - name: Deploy Network
        working-directory: ./environments/${{ env.ENVIRONMENT }}/network
        run: |
          terraform init -upgrade
      - name: Terraform Validate
        working-directory: ./environments/${{ env.ENVIRONMENT }}/network
        run: terraform validate 
      - name: Terraform Plan
        working-directory: ./environments/${{ env.ENVIRONMENT }}/network
        run: |
          terraform plan -var-file="/Infrastructure/environments/${{ env.ENVIRONMENT }}/${{ env.tfvarsFilename }}" -out=ephemeral-${{ env.ENVIRONMENT }}-eks.tfplan  
        
        