name: ephmrl-dev-eks

on:
  repository_dispatch:
    types: [ephmrl-dev-eks]

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: "us-east-1"
  ENVIRONMENT: ${{ github.event.client_payload.config.environment }}
  CLUSTER_NAME: ${{ github.event.client_payload.config.projectName }}
  tfvarsFile: ${{ github.event.client_payload.config.tfvarsFile }}

permissions:
  id-token: write
  contents: read  

jobs:
  developer-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::586098609239:role/GitHubActionsRole
          role-session-name: GitHub-Actions-OIDC-Session
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false

      - name: config_variables
        run: |
          echo "Payload received: ${{ github.event.client_payload.config }}"
          echo "--------------------------------"
          echo "Parameters received from repository dispatch event:"
          echo "##"
          echo "ENVIRONMENT=${{ github.event.client_payload.config.environment }}" >> $GITHUB_OUTPUT
          echo "ClusterName=${{ github.event.client_payload.config.projectName }}" >> $GITHUB_OUTPUT
          echo "Region=${{ github.event.client_payload.config.region }}" >> $GITHUB_OUTPUT
          echo "InstanceType=${{ github.event.client_payload.config.instanceType }}" >> $GITHUB_OUTPUT
          echo "tfvarsfile=${{ github.event.client_payload.config.tfvarsFile }}" >> $GITHUB_OUTPUT
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      # Deploy Network
      - name: Deploy Network
        working-directory: ./environments/${{ env.ENVIRONMENT }}/network
        run: |
          terraform init -upgrade
      - name: Terraform Validate
        working-directory: ./environments/${{ env.ENVIRONMENT }}/network
        run: terraform validate 
      - name: Terraform Plan
        working-directory: ./environments/${{ env.ENVIRONMENT }}/network
        run: |
          terraform plan -var-file="${{ env.tfvarsFile }}" -out=ephemeral-${{ env.ENVIRONMENT }}-eks.tfplan