name: ephmrl-dev-eks

on:
  repository_dispatch:
    types: [ephmrl-dev-eks]

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: "us-east-1"
  PAYLOAD: ${{ toJson(github.event.client_payload.config) }}
  ENVIRONMENT: ${{ github.event.client_payload.config.environment }}
  CLUSTER_NAME: ${{ github.event.client_payload.config.projectName }}
  tfvarsFilename: "${{ github.event.client_payload.config.projectName }}.tfvars"

permissions:
  id-token: write
  contents: read  

jobs:
  developer-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::586098609239:role/GitHubActionsRole
          role-session-name: GitHub-Actions-OIDC-Session
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false

      - name: config_variables
        run: |
          echo "Payload received: ${{ env.PAYLOAD }}"
          echo "--------------------------------"
          jq -r 'to_entries[] | "\(.key)=\(.value)"' <<< "${{ env.PAYLOAD }}" > config.env
          cat config.env
          echo "--------------------------------"
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false


      # Deploy Network
    #  - name: Deploy Network
    #    working-directory: ./environments/${{ env.ENVIRONMENT }}/network
    #    run: |
    #      terraform init -upgrade
    #  - name: Terraform Validate
    #    working-directory: ./environments/${{ env.ENVIRONMENT }}/network
    #    run: terraform validate 
    #  - name: Terraform Plan
    #    run: |
    #      terraform plan -var-file="/infrastructure/${{ env.ENVIRONMENT }}/${{ env.tfvarsFile }}" -out=ephemeral-${{ env.ENVIRONMENT }}-eks.tfplan  
    #    working-directory: ./environments/${{ env.ENVIRONMENT }}/network
        