name: ephmrl-dev-eks

on:
  repository_dispatch:
    types: [ephmrl-dev-eks]

env:
  TF_VERSION: "1.5.0"
  AWS_REGION: "us-east-1"

permissions:
  id-token: write
  contents: read  

jobs:
  developer-eks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::586098609239:role/GitHubActionsRole
          role-session-name: GitHub-Actions-OIDC-Session
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: false

      - name: Check passed in variables
        run: |
          echo "Payload received: ${{ github.event.client_payload.config }}"
          echo "--------------------------------"
          echo "Parameters received from repository dispatch event:"
          echo "##"
          echo "Environment: ${{ github.event.client_payload.config.environment }}"
          echo "Cluster Name: ${{ github.event.client_payload.config.projectName }}"
          echo "Region: ${{ github.event.client_payload.config.region }}"
          echo "Instance Type: ${{ github.event.client_payload.config.instanceType }}"